# Generated by Django 6.0.6 on 2026-08-02 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0002_alter_shop_logo_alter_shop_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('reason', models.CharField(choices=[('initial_stock', 'Initial Stock'), ('sale', 'Sale'), ('cancellation', 'Cancelled (Restored)'), ('manual', 'Manual Adjustment')], max_length=20)),
                ('delta', models.IntegerField()),
                ('resulting_stock', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='products.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', '-created_at'], name='inventory_i_shop_id_e75c40_idx'), models.Index(fields=['product'], name='inventory_i_product_0d970b_idx')],
            },
        ),
    ]
